"""
M3 IdentityOS — Governed tenant module inside KIRP.

All events carry metadata.module = "m3". All state changes are audited.
No M3 action bypasses KIRP governance.
"""

from __future__ import annotations

from src.modules.m3.events import (
    M3_MODULE_TAG,
    EVENT_M3_DAILY_REFLECTION_SUBMITTED,
    EVENT_M3_MICRO_ACTION_GENERATED,
    EVENT_M3_MICRO_ACTION_COMPLETED,
    EVENT_M3_MICRO_ACTION_SNOOZED,
    EVENT_M3_WEEKLY_SYNTHESIS_REQUESTED,
    EVENT_M3_WEEKLY_SYNTHESIS_GENERATED,
    EVENT_M3_MONTHLY_EVOLUTION_REQUESTED,
    EVENT_M3_MONTHLY_EVOLUTION_UPDATED,
    EVENT_M3_IDENTITY_INTENT_DECLARED,
    EVENT_M3_IDENTITY_VECTOR_UPDATED,
    EVENT_M3_GAP_ANALYSIS_COMPUTED,
    EVENT_M3_HUMAN_GOVERNANCE_REQUIRED,
    M3_EVENT_TYPES,
    ensure_m3_metadata,
)

__all__ = [
    "M3_MODULE_TAG",
    "EVENT_M3_DAILY_REFLECTION_SUBMITTED",
    "EVENT_M3_MICRO_ACTION_GENERATED",
    "EVENT_M3_MICRO_ACTION_COMPLETED",
    "EVENT_M3_MICRO_ACTION_SNOOZED",
    "EVENT_M3_WEEKLY_SYNTHESIS_REQUESTED",
    "EVENT_M3_WEEKLY_SYNTHESIS_GENERATED",
    "EVENT_M3_MONTHLY_EVOLUTION_REQUESTED",
    "EVENT_M3_MONTHLY_EVOLUTION_UPDATED",
    "EVENT_M3_IDENTITY_INTENT_DECLARED",
    "EVENT_M3_IDENTITY_VECTOR_UPDATED",
    "EVENT_M3_GAP_ANALYSIS_COMPUTED",
    "EVENT_M3_HUMAN_GOVERNANCE_REQUIRED",
    "M3_EVENT_TYPES",
    "ensure_m3_metadata",
]
